services:
  skc-deck-api:
    image: alpine:latest
    command: ./skc-deck-api
    working_dir: /app
    ports:
      - "9010:9010"
    volumes:
      - "./skc-deck-api:/app/skc-deck-api"
      - "./certs/:/app/certs/"
      - "./.env_prod:/app/.env_prod"
      - "/usr/share/zoneinfo/:/usr/share/zoneinfo/"
      - "./certs/ca_bundle.crt:/etc/ssl/certs/zero-ssl-ca.crt" # trusting zer ssl CA cert in private network
    restart: always
    deploy:
      resources:
        limits:
          memory: 75m
    networks:
      - skc-network
    environment:
      - SKC_DECK_API_DOT_ENV_FILE=.env_prod

networks:
  skc-network:
    name: skc-network
    driver: bridge
    external: true
