services:
  skc-deck-api:
    image: golang:1.22.1-bullseye
    command: go run .
    working_dir: /app
    ports:
      - "9010:9010"
    volumes:
      - "./:/app"
      - "./certs/ca_bundle.crt:/etc/ssl/certs/zero-ssl-ca.crt" # trusting zer ssl CA cert in private network
    restart: always
    deploy:
      resources:
        limits:
          memory: 250m
    networks:
      - skc-network
    environment:
      - SKC_DECK_API_DOT_ENV_FILE=.env_prod

networks:
  skc-network:
    name: skc-network
    driver: bridge
    external: true
